server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anwarr1/external-config-exam-web-services.git
          clone-on-start: true
